name: cab_booking_app
description: A Flutter cab booking application with optimized location search.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  google_maps_flutter: ^2.3.0
  google_maps_flutter_web: ^0.5.4
  equatable: ^2.0.5
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  # intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - .env